name: randweather
# dropped the Docker container use (DLW April 2025)

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: random weather
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      PYTHONPATH: ${{ github.workspace }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libboost-all-dev libeigen3-dev

      - name: make C++
        run: |
          cd cell2fire/Cell2FireC
          make
      - name: Install Python dependencies
        run: pip install -r requirements.txt pytest -e .

      - name: create input data
        run: |
           cd cell2fire
           python main.py --input-instance-folder ../data/Harvest40x40/ --output-folder ../Harvest40x40 --ignitions --sim-years 2 --nsims 5 --grids --finalGrid --weather random --nweathers 200 --Fire-Period-Length 1.0 --output-messages --ROS-CV 0.8 --seed 123 --stats --allPlots --IgnitionRad 1 --combine --HarvestedCells ../data/Harvest40x40/band1_2.csv
      - name: run tests
        run: |
          cd tests
          pytest test_randweather.py 


